name: Create Bug Report
description: Report a bug or crash in Impactor.
title: '[Bug] '
labels:
  - bug

body:
  - type: textarea
    id: text
    attributes:
      label: Report
    validations:
      required: true

  - type: checkboxes
    id: agreement
    attributes:
      label: Contributor Checks
      options:
        - label: I am willing to attempt to make a pull request to fix this bug
          required: false

  - type: checkboxes
    id: extras
    attributes:
      label: Additional Information
      options:
        - label: Developer mode enabled
          required: false
        - label: Using paid developer account
          required: false
        - label: I will send an ipa of the app I'm having trouble installing if any
          required: true
        - label: I'm willing to provide crash logs or debugging information if needed
          required: true
